// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyWebApiKeyForCompilationOnly',
    appId: '1:625509958927:web:625509958927abcdef',
    messagingSenderId: '625509958927',
    projectId: 'project-625509958927',
    authDomain: 'project-625509958927.firebaseapp.com',
    storageBucket: 'project-625509958927.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyAndroidApiKeyForCompilationOnly',
    appId: '1:625509958927:android:625509958927abcdef',
    messagingSenderId: '625509958927',
    projectId: 'project-625509958927',
    storageBucket: 'project-625509958927.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyIosApiKeyForCompilationOnly',
    appId: '1:625509958927:ios:625509958927abcdef',
    messagingSenderId: '625509958927',
    projectId: 'project-625509958927',
    storageBucket: 'project-625509958927.appspot.com',
    iosBundleId: 'com.example.industryLevelEmployeeAttendanceWorkforceManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyMacosApiKeyForCompilationOnly',
    appId: '1:625509958927:ios:625509958927abcdef',
    messagingSenderId: '625509958927',
    projectId: 'project-625509958927',
    storageBucket: 'project-625509958927.appspot.com',
    iosBundleId: 'com.example.industryLevelEmployeeAttendanceWorkforceManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyWindowsApiKeyForCompilationOnly',
    appId: '1:625509958927:windows:625509958927abcdef',
    messagingSenderId: '625509958927',
    projectId: 'project-625509958927',
    storageBucket: 'project-625509958927.appspot.com',
  );
}
